spring:
  application:
    name: CustomerService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LibrarySWA

  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/,
        http://localhost:8762/eureka/

